---
apiVersion: v1
kind: Service
metadata:
  name: scr-service
  labels:
    app: scr-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
    # the port that this service should serve on
  - port: 30770
    targetPort: 30770
    nodePort: 30770
    name: scr
  externalIPs: ["124.46.72.71"]
  selector:
    app: scr-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scr-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scr-service
        tier: backend
    spec:
      containers:
      - name: scr-service
        image: registry.kaaiot.io:5000/scr-service:1.0.0-SNAPSHOT
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: scr-port
          timeoutSeconds: 50
          initialDelaySeconds: 200
          periodSeconds: 50
        readinessProbe:
          httpGet:
            path: /health
            port: scr-port
          timeoutSeconds: 50
          initialDelaySeconds: 50
          periodSeconds: 50
        volumeMounts:
          - name: scr-conf-volume
            mountPath: /srv/scr/
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: general-services-config   # Refer to the SCR service deployment documentation for creating this ConfigMap
        env:
        - name : PRIVATE_DNS_HOST
          value: "10.2.2.45" #cybervision dns
        - name: CONFIGURATION_REPOSITORY_URL
          value: https://gitlab.kaaiot.io/evangelism/solutions/smart-energy/blueprint.git
        - name: CONFIGURATION_REPOSITORY_USERNAME
          value: "webui-test"
        - name: CONFIGURATION_REPOSITORY_PASSWORD
          value: "webui-pass"
        - name: CONFIGURATION_REPOSITORY_SEARCH_PATHS
          value: "/scr"
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "60"    # -1 means unlimited timeout
        - name: JMX_PORT
          value: "30771"
        - name: JMX_MONITOR_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jmx-monitor-credentials   # Refer to the SCR service deployment documentation for creating this Secret
              key: password
        - name: JAVA_OPTIONS
          value: -Xmx700m
        - name: APP_CONFIG_PATH
          value: /srv/scr/service-config.yml
        ports:
        - name: scr-port
          containerPort: 30770
        - name: jmx-port
          containerPort: 30771
      volumes:
        - name: scr-conf-volume
          configMap:
            name: scr-service-config
            items: 
            - key: scr-config
              path: service-config.yml
